### ISSUE TITLE
Provide send_message function to handlers

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#132]
Handlers have to send messages, but we don't provide a consistent way to do it. Right now there are three handlers (Syscall, Wolfram, and Admin) that each have their own implementation of `send_message`

**Comment by Kileak** [comment]
The consistent way is `slack_wrapper.post_message(channel_id, msg)`.

The different handlers have their own implementation just for being able to configure it for every handler, if the message should be sent to channel or to the user via dm.

But I'd agree, that we don't need really need that configuration options, since it always uses the default from code anyways, so we could just remove those `send_message` calls, and replace them with corresponding `slack_wrapper.post_message` calls.

**Comment by Kileak** [comment]
Removed the `send_message` functions and replaced them with `post_message` in ad8d7f91e1fdf9bdfde313e8e14962e814a5a4da
