### ISSUE TITLE
If the OTA long name is a link it looks weird in status

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#200]
`#allmn19 : _<http://ALL.MN|ALL.MN> 2019_  [0 solved / 0 total]****`

**Comment by Kileak** [comment]
It's not a link, it's slack interpreting it as a link, because it contains a dot and parse it as a url.

We could fix the display by setting no parsing for status output, but slack will still convert this into a clickable link (which will just lead nowhere).

Maybe also not allowing dots in a ctf long name, so slack will not be able to misinterpret the long name at all.
