### ISSUE TITLE
Increase channel length

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#209]
Slack now allows channel length to be 80 characters! https://slackhq.com/new-slack-features-search-calls-channels

**Comment by Grazfather** [comment]
Purpose length limit is 250 characters.

We already get close to this, though we can save a few bytes

`{“ota_bot”: “OTABOT”, “name”: “defcamp19", “type”: “CTF”, “cred_user”: “ctf@opentoallctf.com”, “cred_pw”: “aaaaaaaaaaaaaaaaaa”, “long_name”: “defcamp19", “finished”: true, “finished_on”: 1567961724.5042982}`

This is 206 of 250 already.

Here's what we can do:
1. Second granularity on the time... save what looks like 8 characters.
2. make the ota_bot field value empty. 6 characters (or `true`, saving 4)
3. Cap the length of the other fields.
With the variable length fields removed and the trimming done:

`{"ota_bot": true, "name": "", "type": "CTF", "cred_user": "", "cred_pw": "", "long_name": "", "finished": true, "finished_on": 1567961724}`

This is 138.

Now we have to fill in

- name: We want up to 40 ideally
- cred_user: our email is 20 alone. probably 30
- cred_pw: 20 should be fine
- long_name: 40, or maybe we can get rid of it

that's 40 + 30 + 20 + 40 = 130
+138 = 268.

That means 18 characters to shed to fit into 250
'cred_user' and 'cred_pw' to 'user' and 'pw' saves 10 alone. ditching spaces would do the rest.

_or_ we just ditch the long name.

I say we ditch the long name, but we also should put caps on the creds length (user and pw).

@Kileak what do you think?

**Comment by Kileak** [comment]
Good idea on shortening the time, also removing the whitespaces.

Mabye `"ota_bot":1`

But I would put no caps on creds, if someone accidentially used something longer, we would run into a problem.

Also long name should be kept for SolveTracker post later on (We could also make long_name a mandatory parameter for !archivectf, but that would be strange, if no git support is enabled). 

Also I like the long name on the status list :)

`name` should be short imo, just because you *can* create a 40 character channel, doesn't mean you should (just my opinion). I would still prefer short channel names and descriptive long name.

I think removing the restriction and shortening the purpose is a good idea anyways, so it doesn't break, just because someone used some characters too much, but I wouldn't expect someone to use the complete available length.

**Comment by Grazfather** [comment]
I'm OK with keeping the longer long name cap. We still should cap the rest. We don't want to create a CTF and then have it fail when setting the purpose.

I pushed a PR #211 to save a few characters, but this was done blind, will maybe cap the rest this weekend.
