### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Grazfather** [OpenToAllCTF/OTA-Challenge-Bot#49]

**Comment by Kileak** [comment]
This is a pretty good idea and should get some priority, since connecting to a test slack and testing all commands just to make sure, there's not a missing rename of a variable gets quite time consuming with every new feature.

How should we start this? Didn't do any tests by now in python, any good readups or can someone create some boilerplate code?

**Comment by Kileak** [comment]
Look at #174 for this one
